### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by stefanpenner**
- [x] fix failing tests
- [ ] get feedback
- [ ] test in real app

### CODE REVIEW

**Comment by chriseppstein** [comment]
The code refactor looks good. But the tests are broken with an error `"You must implement updateCache."`

**Comment by stefanpenner** [comment]
@chriseppstein did you test against b07c3ac ?

**Comment by stefanpenner** [comment]
@chriseppstein I suspect you have a stale repo, or node_modules. broccoli-caching-writer 2.0 has no `updateCache` https://github.com/ember-cli/broccoli-caching-writer/blob/c4e11bcd46cb5b6692b3f8327948a56ad316c2e2/CHANGELOG.md#200

**Comment by chriseppstein** [comment]
@stefanpenner Thanks. That fixed it. I've merged the PR and released 2.0.0

**Pull request merged**
